# YokeFlow Configuration - Playwright Docker Enabled

models:
  initializer: claude-opus-4-5-20251101
  coding: claude-sonnet-4-5-20250929

timing:
  auto_continue_delay: 3
  web_ui_poll_interval: 5

sandbox:
  type: docker
  docker_image: yokeflow-playwright:latest  # Using Playwright-enabled image
  docker_network: bridge
  docker_memory_limit: 3g  # Increased for browser operations
  docker_cpu_limit: 2.0
  docker_ports: []  # No port forwarding needed - Playwright runs inside container!

project:
  default_generations_dir: generations
  max_iterations: null  # unlimited
